name: Actions Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              id: greet
              uses: actions/hello-world-javascript- actions@v1
              with:
                  who-to-greet: Mike Abdul
            - name: Log Greetings Time
              run: echo "${{ steps.greet.outputs.time }}
