name: Shell Commands Check

on: [push]

jobs:
    run-shell-command-check:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello, Shell"
            - name: multiline script
              run: |
                  node -v
                  npm -v
            - name: python Command
              run: |
                  import platform
                  print(platform.processor())
              shell: python
    run-windows-command-check:
        runs-on: windows-latest
        needs: ["run-shell-command-check"]
        steps:
            - name: Directory Powershell
              run: Get-Location
            - name: Directory Bash
              run: pwd
              shell: bash
