name: Shell Commands Check

on: [push]

jobs:
    run-shell-command-check:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: eccho "Hello, Shell"
            - name: multiline script
              run: |
                  node -v
                  npm -v
